name: Check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025-vs2026
            target: x86_64-pc-windows-msvc
          - os: windows-11-vs2026-arm
            target: aarch64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: jdx/mise-action@v4
        with:
          install: true

      - run: rustup target add ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - run: cargo test --locked --target ${{ matrix.target }}

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - uses: jdx/mise-action@v4
        with:
          install: true

      - uses: Swatinem/rust-cache@v2
        with:
          key: x86_64-unknown-linux-gnu

      - run: mise run check
